apiVersion: v1
kind: Service
metadata:
  namespace: lesson14
  name: my-service
spec:
  selector:
    app: goweb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

#LoadBalancer

#apiVersion: v1
#kind: Service
#metadata:
#  name: my-balancer
#  namespace: lesson14
#spec:
#  ports:
#    - port: 80
#      name: webport
#      targetPort: 8080
#  selector:
#    app: goweb
#  type: LoadBalancer
#  loadBalancerIP: 10.10.130.145

#NodePort

#apiVersion: v1
#kind: Service
#metadata:
#  name: nodeport-goapp-service
#  namespace: lesson14
#selector:
#  app: goapp
#spec:
#  type: NodePort
#  ports:
#    - name: http
#      port: 80
#      targetPort: 8080
#      nodePort: 30050
#      protocol: TCP